# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
minimal_mistakes_skin: "mint"
locale: "en-US"
title: Zeynep Enkavi
title_separator: "-"
email: zenkavi@stanford.edu
description: >- # this means to ignore newlines until "baseurl:"
  Neuroeconomics. Self-regulation. Meta-analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zeynepenkavi
github_username:  zenkavi

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# Custom front matter defaults
defaults:
  -
    scope:
      path: "" #empty string applies these defaults to all files on the site
      type: "posts"
    values:
      layout: single
      title: "Default Title"
      author_profile: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Minimal mistakes settings: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
name: "Zeynep Enkavi"
repository: "zenkavi/zenkavi.github.io"

author:
  name: Zeynep Enkavi
  avatar: "assets/images/bio.jpeg"
  bio: "Stanford Psychology PhD Candidate interested in neuroeconomics, self-regulation and meta-analysis."
  links:
    - label: ""
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:zenkavi@stanford.edu
    - label: ""
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=RbsrblkAAAAJ&hl=en&oi=ao"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zeynepenkavi"
    - label: ""
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/zenkavi"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zenkavi"
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/zenkavi"

footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=RbsrblkAAAAJ&hl=en&oi=ao"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zeynepenkavi"
    - label: ""
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/zenkavi"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zenkavi"
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/zenkavi"

include:
  - .htaccess
  - _pages

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/


whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

style: kjhealy

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
