# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
minimal_mistakes_skin: "mint"
locale: "en-US"
title:
title_separator: "-"
name: ""
email: zenkavi@caltech.edu
description: >- # this means to ignore newlines until "baseurl:"
  Neuroeconomics. Self-regulation. Meta-analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zenkavi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zeynepenkavi
github_username:  zenkavi
future: true

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Custom front matter defaults
defaults:
  -
    scope:
      path: "" #empty string applies these defaults to all files on the site
      type: "posts"
    values:
      layout: single
      title: "Default Title"
      author_profile: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Minimal mistakes settings: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
name: "Zeynep Enkavi"
repository: "zenkavi/zenkavi.github.io"

author:
  name: A. Zeynep Enkavi
  avatar: "assets/images/headshot.jpg"
  bio: "Postdoctoral scholar in Neuroeconomics at Caltech"
  links:
    - label: ""
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:zenkavi@caltech.edu
    - label: ""
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=RbsrblkAAAAJ&hl=en&oi=ao"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zeynepenkavi"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zenkavi"

footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=RbsrblkAAAAJ&hl=en&oi=ao"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zeynepenkavi"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zenkavi"

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

style: kjhealy
